language: node_js
node_js:
  - "10"

sudo: true
dist: trusty

branches:
  only:
    - master

before_script:


jobs:
  include:
    - stage: Run syntax check (tslint) and tests
      script:
        - cd bogenliga
        - npm ci
        - npm install
        - ng lint
        # PREPARE TESTS
        #- cd bogenliga
        #- export CHROME_BIN=/usr/bin/google-chrome
        #- export DISPLAY=:99.0
        #- sh -e /etc/init.d/xvfb start
        #- sudo apt-get update
        #- sudo apt-get install -y libappindicator1 fonts-liberation
        #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #- sudo dpkg -i google-chrome*.deb
        # TESTS
        #- npm ci
        #- npm install
        #- ng test --watch false
        #- npm run e2e
        - echo "Skip tests"
    - stage: Build and deploy application
      script:
        - cd bogenliga
        - npm ci
        - npm install
        - ng build --prod^--configuration=offline --base-href "https://exxcellent.github.io/swt2-bsa-frontend/" --deploy-url "https://exxcellent.github.io/swt2-bsa-frontend/"
      # DEPLOY GITHUB PAGES
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: bogenliga/dist/bogenliga
        verbose: true
        keep-history: true
        on:
          branch: master
